### ISSUE TITLE
Add ability to stop/resume training

### ISSUE THREAD

**Issue by gautams3** [rail-berkeley/serl#26]
It would be good to have the ability to pause, stop, and resume training. As part of the stop, it would be good to have the option to save training state (including replay buffers, optimizer state, etc.). This might also involve changes in `agentlace` by @youliangtan .

Edit: added separate options for pausing v/s stopping training

**Comment by youliangtan** [comment]
The checkpoint is currently saved on every interval with the `--checkpoint_period` flag

To address the saving&loading of replay buffer, i opened a PR to address this: https://github.com/rail-berkeley/serl/pull/27
Instead saving it with a pkl file, this saves the data in the replay buffer with the standardized [rlds](https://github.com/google-research/rlds) format, which is also compatible with the RTX data.

This is implemented in the `frank_env` simulation env examples, along with updated documentation. Let me know after trying it out.

**Comment by youliangtan** [comment]
I merged the #27 PR, similar implementation can be implemented in the non-sim env. feel free to try it out

**Comment by jianlanluo** [comment]
since the PR is checked in, should we close this issue?
