### ISSUE TITLE
What changes to make if I have no demo data

### ISSUE THREAD

**Issue by shivanshpatel35** [rail-berkeley/serl#33]
Hi,

I don't have demo data for real-world experiments. So, I did not load any demo file. What changes should I make so the algorithm will not sample data from demos? Will commenting the lines that incorporate prior data [[1](https://github.com/rail-berkeley/serl/blob/main/examples/async_peg_insert_drq/async_drq_randomized.py#L276), [2](https://github.com/rail-berkeley/serl/blob/main/examples/async_peg_insert_drq/async_drq_randomized.py#L286)] suffice?

**Comment by jianlanluo** [comment]
it will likely not working well if no demo there. so please record 10-20 demo as instructed
