### ISSUE TITLE
Support for Mujoco XLA

### ISSUE THREAD

**Issue by shivanshpatel35** [rail-berkeley/serl#37]
Hi,
Do you plan to support [Mujoco XLA](https://mujoco.readthedocs.io/en/stable/mjx.html) for simulation training in the near future?

**Comment by jianlanluo** [comment]
The simulator used in SERL is mainly for debugging purpose, we don't currently have a plan to further develop it. You are welcome to open a PR if you find adding Mujoco XLA is generically beneficial.
