### ISSUE TITLE
ADD TIME STEPS

### ISSUE THREAD

**Issue by HM102** [rail-berkeley/serl#53]
Is there a simple way to add timesteps as another key in the RLDS record directly in the data collection pipeline

**Comment by youliangtan** [comment]
how are you recording your rlds data? Here we provided 2 examples of recording prior data for rlpd. 1) pkl files 2) tf rlds format.

**Comment by HM102** [comment]
using rlds

**Comment by youliangtan** [comment]
If you are converting your data from your own pkl or dataformat. You can use [this](https://github.com/kpertsch/rlds_dataset_builder/blob/cff9f536c53518baa744b0f31e66d53ef445d2a1/example_dataset/example_dataset_dataset_builder.py#L76-L81) dataset builder as a reference.

If you are using `oxe_envlogger` for gym env logging, can use [set_step_metadata() api](https://github.com/rail-berkeley/oxe_envlogger/blob/062c794ce9651cd5ef68042be21c1642ab69fe37/oxe_envlogger/envlogger.py#L182-L187) to add a metadata to each step.
