### ISSUE TITLE
Question about the hyperparameters used in the experiments

### ISSUE THREAD

**Issue by BurakDmb** [rail-berkeley/serl#55]
Hi,

Thank you for your efforts in the SERL paper and the repo. 

I want to ask if you used the same hyperparameters in the experiments in the paper with the examples in this repo.

If different, what values did you use for these parameters:
`Network size`, `discount rate`, `temperature_init`, `utd_ratio`, and the `encoder type`?

**Comment by youliangtan** [comment]
IIRC all the hyperparameters provided here are default used in those experiments. @Leo428  can correct me if Im wrong.

**Comment by Leo428** [comment]
hi @BurakDmb,
the hyperparams for each task and experiment is specified in the .sh files. For example, [here](https://github.com/rail-berkeley/serl/blob/main/examples/async_sac_state_sim/run_learner.sh)
