### ISSUE TITLE
Variable control frequency

### ISSUE THREAD

**Issue by zichunxx** [rail-berkeley/serl#74]
Hi! Thanks for your great work and sharing!

In sec.4.5 of your paper, the variable control frequency is proposed to realize precise movement control. 

However, I found this idea does not seem to be implemented in this repo because the `control_dt` and `physics_dt` are both fixed.

As shown in 

https://github.com/rail-berkeley/serl/blob/21ff8a018d77ac8ee8505cfda11c567702ee70b0/franka_sim/franka_sim/mujoco_gym_env.py#L34-L36

and 

https://github.com/rail-berkeley/serl/blob/21ff8a018d77ac8ee8505cfda11c567702ee70b0/franka_sim/franka_sim/envs/panda_pick_gym_env.py#L205-L217

, the `step` function does not change the loop times to control the run times of the downstream controller. 

Looking forward to your reply! Thanks in advance!

**Comment by jianlanluo** [comment]
I am not sure what you mean by variable control frequency, dt is fixed for
all experiments. Section 4.3 is about reset free RL

**Comment by jianlanluo** [comment]
Thats not the controller frequency, its bounding the reference from the
impedance controller

**Comment by jianlanluo** [comment]
Its clamping the reference set by upstream RL, detailed in section 4.5.
Nothing to do with frequency

**Comment by jianlanluo** [comment]
https://github.com/rail-berkeley/serl_franka_controllers

**Comment by jianlanluo** [comment]
Only with Franka, in sim you dont need this
