### ISSUE TITLE
is it possible to change the franka robot to another robot (Aloha arm)?

### ISSUE THREAD

**Issue by cong1024** [rail-berkeley/serl#75]
Thanks for the great work in RL for real robot, Now I want to change the franka robot to my own aloha arm, Do you guys think that it possible to achieve and perfoms also good?

**Comment by jianlanluo** [comment]
We haven’t tried that, my sense is that it wouldn’t be that easy.

**Comment by parzivar** [comment]
is it possible to change the robot to franka research 3 robot

**Comment by Leo428** [comment]
@parzivar It should work on franka research 3 robot.

**Comment by parzivar** [comment]
> @parzivar It should work on franka research 3 robot.

thank u bro！！！
Could you please tell me the main configuration of the environment?
such as Ubuntu version、cuda。Because I had a problem configuring jax 12 when traning in simulation.
Thanks!!
