### ISSUE TITLE
Flax and Jax can/need to be updated for current installs on windows

### ISSUE THREAD

**Issue by DTSills** [rail-berkeley/serl#78]
Current installs of Jax deprecates an experimental function used by the "requirements.txt" defined version of Flax. Flax should be updated to resolve issue and I would like to recommend updating the requirements.txt in the serl_launcher

I have installed this package on two systems, one with jax cpu version and a second with jax gpu. With the gpu I struggled to install the specified version of Jax defined in the installation instructions and went with the "current" one. With both installs however, in the core/meta.py file for the Flax version defined in the requirements document, there is an experimental.map function used which has been deprecated by Jax. This has been updated by Flax and the resolution is to simply update Flax.

Love this project. I am using it on my Masters Thesis at the University of Louisville. Expect to see a citation at the beginning of next year. Thank you all.

**Comment by jianlanluo** [comment]
we don't support windows
